<!DOCTYPE html>
<html>
<head>


    <title>Search </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<style>
body{
    background:;
}
.container{
    margin-top:100px;
}
.glyphicon-search{
    font-size:20px;
}
.btn-default{
    background:orange;
    width:100px;
    padding:12.5px;
}
.form-control{
    padding:25px;
    font-size:20px;
}

</style>




</head>
<body>
<div class ="container">
<form>
  <div class ="input-group">
     <input type ="text" class ="form-control" placeholder ="Search" name ="search">
      <div class ="input-group-btn">
      <button class ="btn btn-default" type ="submit">
      <i class ="glyphicon glyphicon-search"></i></button>
      </div>
      </div>
      </form>
</body>
</html>